# General Site Settings
title: Your Name
description: >-
  Short site description goes here.
email: your-email@domain.com
url: "https://YOUR_USERNAME.github.io"
baseurl: "" # User/org site uses empty baseurl

# Author Settings
author:
  name: Your Name
  title: Your Title
  photo: myPhoto.jpg # Place this image in assets/images/
  bio: >-
    Brief bio goes here. Mention your research focus, expertise, or interests.
  cv: "assets/uploads/cv.pdf" # Replace with your actual CV file path

# Social Links (Leave empty if not using)
social:
  email: your-email@domain.com
  linkedin: https://www.linkedin.com/in/username
  x_twitter: https://x.com/username
  google_scholar: https://scholar.google.com/citations?user=Example
  researchgate: https://www.researchgate.net/profile/username
  orcid: https://orcid.org/0000-0000-0000-0000
  website: https://YOUR_USERNAME.github.io
